version: '3.8'
services:
  database:
    container_name: work-app-db
    restart: unless-stopped
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: workapp
      POSTGRES_PASSWORD: workapp
      POSTGRES_DB: workapp
      TZ: Europe/Warsaw
    volumes:
      - ./data:/var/lib/postgresql/data
  database-test:
    container_name: work-app-test-db
    restart: unless-stopped
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: workapp
      POSTGRES_PASSWORD: workapp
      POSTGRES_DB: workapp-test
      TZ: Europe/Warsaw
    volumes:
      - ./data-test:/var/lib/postgresql/data
